### ISSUE TITLE
Multiclass Error => RuntimeError: There was an error in the TPOT optimization process

### ISSUE THREAD

**Issue by jmrichardson** [EpistasisLab/tpot#1153]
Hi, I am trying to get a simple multiclass classification example working.  Referencing #665 , this code doesn't work:

```
from sklearn.datasets import make_classification
from tpot import TPOTClassifier

X, y = make_classification(n_samples=200, n_features=100,
                           n_informative=20, n_redundant=10,
                           n_classes=3, random_state=42)
tpot = TPOTClassifier(generations=10, population_size=20, verbosity=20, scoring='f1_macro')
tpot.fit(X, y)
```
 Results in this error:

```
Generation 1 - Current best internal CV score: -inf
                                                                             D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\model_selection\_split.py:668: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)
D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\model_selection\_split.py:668: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)
D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\model_selection\_split.py:668: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)
D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\model_selection\_split.py:668: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)
D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\model_selection\_split.py:668: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)
D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\model_selection\_split.py:668: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)
D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\model_selection\_split.py:668: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)
D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\model_selection\_split.py:668: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)
D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\model_selection\_split.py:668: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)
D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\model_selection\_split.py:668: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)
Traceback (most recent call last):
  File "D:\Anaconda3\envs\tactory\lib\site-packages\tpot\base.py", line 742, in fit
    log_file=self.log_file_
  File "D:\Anaconda3\envs\tactory\lib\site-packages\tpot\gp_deap.py", line 281, in eaMuPlusLambda
    per_generation_function(gen)
  File "D:\Anaconda3\envs\tactory\lib\site-packages\tpot\base.py", line 1052, in _check_periodic_pipeline
    self._update_top_pipeline()
  File "D:\Anaconda3\envs\tactory\lib\site-packages\tpot\base.py", line 838, in _update_top_pipeline
    raise RuntimeError('There was an error in the TPOT optimization '
RuntimeError: There was an error in the TPOT optimization process. This could be because the data was not formatted properly, or because data for a regression problem was provided to the TPOTClassifier object. Please make sure you passed the data to TPOT correctly. If you enabled PyTorch estimators, please check the data requirements in the online documentation: https://epistasislab.github.io/tpot/using/
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\Anaconda3\envs\tactory\lib\site-packages\IPython\core\interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-6e69b03573b8>", line 12, in <module>
    tpot.fit(X_train, y_train)
  File "D:\Anaconda3\envs\tactory\lib\site-packages\tpot\base.py", line 773, in fit
    raise e
  File "D:\Anaconda3\envs\tactory\lib\site-packages\tpot\base.py", line 764, in fit
    self._update_top_pipeline()
  File "D:\Anaconda3\envs\tactory\lib\site-packages\tpot\base.py", line 838, in _update_top_pipeline
    raise RuntimeError('There was an error in the TPOT optimization '
RuntimeError: There was an error in the TPOT optimization process. This could be because the data was not formatted properly, or because data for a regression problem was provided to the TPOTClassifier object. Please make sure you passed the data to TPOT correctly. If you enabled PyTorch estimators, please check the data requirements in the online documentation: https://epistasislab.github.io/tpot/using/
```

I am using version TPOT==0.11.6.post3

In my use case code, I am getting a similar but different error:

```
tpot = TPOTClassifier(population_size=5, generations=4, verbosity=20, scoring='f1_macro')
tpot.fit(X_train, y_train)
```

```
32 operators have been imported by TPOT.
Imputing missing values in feature set
_pre_test decorator: _random_mutation_operator: num_test=0 Solver lbfgs supports only dual=False, got dual=True.
                                                                            D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\model_selection\_split.py:668: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)
D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\model_selection\_split.py:668: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)
D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\model_selection\_split.py:668: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)
D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\model_selection\_split.py:668: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)
D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\model_selection\_split.py:668: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)
D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\model_selection\_split.py:668: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)
D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\model_selection\_split.py:668: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)
D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\model_selection\_split.py:668: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)
D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\model_selection\_split.py:668: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)
D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\model_selection\_split.py:668: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)
Traceback (most recent call last):
  File "D:\Anaconda3\envs\tactory\lib\site-packages\tpot\base.py", line 742, in fit
    log_file=self.log_file_
  File "D:\Anaconda3\envs\tactory\lib\site-packages\tpot\gp_deap.py", line 281, in eaMuPlusLambda
    per_generation_function(gen)
  File "D:\Anaconda3\envs\tactory\lib\site-packages\tpot\base.py", line 1052, in _check_periodic_pipeline
    self._update_top_pipeline()
  File "D:\Anaconda3\envs\tactory\lib\site-packages\tpot\base.py", line 836, in _update_top_pipeline
    error_score="raise")
  File "D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\model_selection\_validation.py", line 445, in cross_val_score
    error_score=error_score)
  File "D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\model_selection\_validation.py", line 252, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "D:\Anaconda3\envs\tactory\lib\site-packages\joblib\parallel.py", line 1029, in __call__
    if self.dispatch_one_batch(iterator):
  File "D:\Anaconda3\envs\tactory\lib\site-packages\joblib\parallel.py", line 847, in dispatch_one_batch
    self._dispatch(tasks)
  File "D:\Anaconda3\envs\tactory\lib\site-packages\joblib\parallel.py", line 765, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "D:\Anaconda3\envs\tactory\lib\site-packages\joblib\_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "D:\Anaconda3\envs\tactory\lib\site-packages\joblib\_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "D:\Anaconda3\envs\tactory\lib\site-packages\joblib\parallel.py", line 253, in __call__
    for func, args, kwargs in self.items]
  File "D:\Anaconda3\envs\tactory\lib\site-packages\joblib\parallel.py", line 253, in <listcomp>
    for func, args, kwargs in self.items]
  File "D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\utils\fixes.py", line 222, in __call__
    return self.function(*args, **kwargs)
  File "D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\model_selection\_validation.py", line 620, in _fit_and_score
    test_scores = _score(estimator, X_test, y_test, scorer, error_score)
  File "D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\model_selection\_validation.py", line 674, in _score
    scores = scorer(estimator, X_test, y_test)
  File "D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\metrics\_scorer.py", line 88, in __call__
    *args, **kwargs)
  File "D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\metrics\_scorer.py", line 236, in _score
    y_pred = method_caller(estimator, "predict", X)
  File "D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\metrics\_scorer.py", line 53, in _cached_call
    return getattr(estimator, method)(*args, **kwargs)
  File "D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\utils\metaestimators.py", line 120, in <lambda>
    out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)
  File "D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\pipeline.py", line 419, in predict
    return self.steps[-1][-1].predict(Xt, **predict_params)
  File "D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\neighbors\_classification.py", line 197, in predict
    neigh_dist, neigh_ind = self.kneighbors(X)
  File "D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\neighbors\_base.py", line 683, in kneighbors
    (n_samples_fit, n_neighbors)
ValueError: Expected n_neighbors <= n_samples,  but n_samples = 40, n_neighbors = 51
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\Anaconda3\envs\tactory\lib\site-packages\IPython\core\interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-a28618cba5a2>", line 45, in <module>
    tpot.fit(X_train, y_train)
  File "D:\Anaconda3\envs\tactory\lib\site-packages\tpot\base.py", line 773, in fit
    raise e
  File "D:\Anaconda3\envs\tactory\lib\site-packages\tpot\base.py", line 764, in fit
    self._update_top_pipeline()
  File "D:\Anaconda3\envs\tactory\lib\site-packages\tpot\base.py", line 836, in _update_top_pipeline
    error_score="raise")
  File "D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\model_selection\_validation.py", line 445, in cross_val_score
    error_score=error_score)
  File "D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\model_selection\_validation.py", line 252, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "D:\Anaconda3\envs\tactory\lib\site-packages\joblib\parallel.py", line 1029, in __call__
    if self.dispatch_one_batch(iterator):
  File "D:\Anaconda3\envs\tactory\lib\site-packages\joblib\parallel.py", line 847, in dispatch_one_batch
    self._dispatch(tasks)
  File "D:\Anaconda3\envs\tactory\lib\site-packages\joblib\parallel.py", line 765, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "D:\Anaconda3\envs\tactory\lib\site-packages\joblib\_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "D:\Anaconda3\envs\tactory\lib\site-packages\joblib\_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "D:\Anaconda3\envs\tactory\lib\site-packages\joblib\parallel.py", line 253, in __call__
    for func, args, kwargs in self.items]
  File "D:\Anaconda3\envs\tactory\lib\site-packages\joblib\parallel.py", line 253, in <listcomp>
    for func, args, kwargs in self.items]
  File "D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\utils\fixes.py", line 222, in __call__
    return self.function(*args, **kwargs)
  File "D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\model_selection\_validation.py", line 620, in _fit_and_score
    test_scores = _score(estimator, X_test, y_test, scorer, error_score)
  File "D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\model_selection\_validation.py", line 674, in _score
    scores = scorer(estimator, X_test, y_test)
  File "D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\metrics\_scorer.py", line 88, in __call__
    *args, **kwargs)
  File "D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\metrics\_scorer.py", line 236, in _score
    y_pred = method_caller(estimator, "predict", X)
  File "D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\metrics\_scorer.py", line 53, in _cached_call
    return getattr(estimator, method)(*args, **kwargs)
  File "D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\utils\metaestimators.py", line 120, in <lambda>
    out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)
  File "D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\pipeline.py", line 419, in predict
    return self.steps[-1][-1].predict(Xt, **predict_params)
  File "D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\neighbors\_classification.py", line 197, in predict
    neigh_dist, neigh_ind = self.kneighbors(X)
  File "D:\Anaconda3\envs\tactory\lib\site-packages\sklearn\neighbors\_base.py", line 683, in kneighbors
    (n_samples_fit, n_neighbors)
ValueError: Expected n_neighbors <= n_samples,  but n_samples = 40, n_neighbors = 51
```

Thanks for any help

**Comment by jmrichardson** [comment]
Hi,

I also just tried the [example ](https://github.com/EpistasisLab/tpot/blob/master/tutorials/IRIS.ipynb )IRIS dataset and got the similar errors:
```

from tpot import TPOTClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
iris = load_iris()
iris.data[0:5], iris.target
Out[3]: 
(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2]]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]))
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target,
                                                    train_size=0.75, test_size=0.25)
X_train.shape, X_test.shape, y_train.shape, y_test.shape
Out[4]: ((112, 4), (38, 4), (112,), (38,))
tpot = TPOTClassifier(verbosity=2, max_time_mins=2)
tpot.fit(X_train, y_train)
                                                                              
Generation 1 - Current best internal CV score: -inf
                                                                              Traceback (most recent call last):
  File "D:\Anaconda3\envs\tactory\lib\site-packages\tpot\base.py", line 742, in fit
    log_file=self.log_file_
  File "D:\Anaconda3\envs\tactory\lib\site-packages\tpot\gp_deap.py", line 281, in eaMuPlusLambda
    per_generation_function(gen)
  File "D:\Anaconda3\envs\tactory\lib\site-packages\tpot\base.py", line 1052, in _check_periodic_pipeline
    self._update_top_pipeline()
  File "D:\Anaconda3\envs\tactory\lib\site-packages\tpot\base.py", line 838, in _update_top_pipeline
    raise RuntimeError('There was an error in the TPOT optimization '
RuntimeError: There was an error in the TPOT optimization process. This could be because the data was not formatted properly, or because data for a regression problem was provided to the TPOTClassifier object. Please make sure you passed the data to TPOT correctly. If you enabled PyTorch estimators, please check the data requirements in the online documentation: https://epistasislab.github.io/tpot/using/
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\Anaconda3\envs\tactory\lib\site-packages\IPython\core\interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-fc63521ba7ad>", line 1, in <module>
    tpot.fit(X_train, y_train)
  File "D:\Anaconda3\envs\tactory\lib\site-packages\tpot\base.py", line 773, in fit
    raise e
  File "D:\Anaconda3\envs\tactory\lib\site-packages\tpot\base.py", line 764, in fit
    self._update_top_pipeline()
  File "D:\Anaconda3\envs\tactory\lib\site-packages\tpot\base.py", line 838, in _update_top_pipeline
    raise RuntimeError('There was an error in the TPOT optimization '
RuntimeError: There was an error in the TPOT optimization process. This could be because the data was not formatted properly, or because data for a regression problem was provided to the TPOTClassifier object. Please make sure you passed the data to TPOT correctly. If you enabled PyTorch estimators, please check the data requirements in the online documentation: https://epistasislab.github.io/tpot/using/
```

**Comment by weixuanfu** [comment]
Which version of scikit-learn and tpot is in your environment? I doubt that the latest version of scikit-learn (0.24) has a incompatible issue. If you are using 0.24, please downgrade to 0.23.2 for another test.

**Comment by jmrichardson** [comment]
Hi, yes i just referenced #1148 and noticed the similar issue.  Downgraded to 0.23.2 and now all is good :)  thanks for the help!
