### ISSUE TITLE
Submodule import deprecation in scikit-learn 0.24.0

### ISSUE THREAD

**Issue by rachitk** [EpistasisLab/tpot#1176]
## Context of the issue

Currently, the scikit-learn dependency is set to accept all versions >=0.22.0; however, in 0.24.0 functions were moved from several submodules into their main modules. Until this is fixed in TPOT, the scikit-learn dependency may need to be set to accept only versions >=0.22.0 and <0.24.0 in both requirements.txt and setup.py.

https://github.com/EpistasisLab/tpot/blob/6448bdb71ba08b4a0447c640d2f05a05e1affc21/requirements.txt#L4
https://github.com/EpistasisLab/tpot/blob/6448bdb71ba08b4a0447c640d2f05a05e1affc21/setup.py#L40

## Process to reproduce the issue

1. Run nosetests on an up-to-date version of TPOT
2. Tests in https://github.com/EpistasisLab/tpot/blob/master/tests/one_hot_encoder_tests.py will not run due to this line: https://github.com/EpistasisLab/tpot/blob/master/tests/one_hot_encoder_tests.py#L33

## Expected result

All tests should pass with no import errors.

## Current result

Tests in this file error with the following (taken from a Travis run):

```
======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'sklearn.utils.testing')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/testenv/lib/python3.7/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/travis/miniconda/envs/testenv/lib/python3.7/site-packages/nose/loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/miniconda/envs/testenv/lib/python3.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/miniconda/envs/testenv/lib/python3.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/miniconda/envs/testenv/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/home/travis/miniconda/envs/testenv/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/travis/build/EpistasisLab/tpot/tests/one_hot_encoder_tests.py", line 33, in <module>
    from sklearn.utils.testing import assert_array_almost_equal
ModuleNotFoundError: No module named 'sklearn.utils.testing'
```

All other imports of sklearn submodules will likely also fail. #1171 may also be due to this issue.

## Possible fix

Temporarily change the scikit-learn requirement in requirements.txt and setup.py to require versions >=0.22 and <0.24 (not inclusive of 0.24). For a permanent fix, all scikit-learn imports will need to be inspected to ensure compliance with the current API.

**Comment by JDRomano2** [comment]
This seems to be resolved by #1161, which has been merged into `development` but hasn't yet made its way into `master`. The solution was to use `assert_array_almost_equal` from Numpy instead of from scikit-learn
