### ISSUE TITLE
Cannot install TPOT under python 3.5 environment

### ISSUE THREAD

**Issue by CBrauer** [EpistasisLab/tpot#1210]
Hey,

I'm running on Windows 10 Version, 10.0.19042 Build 19042, and Anaconda Python,

I need to run TPOT in a python 3.5 environment (Don't ask... its a long story).
I created a new environment and activated it:

```
(base) H:>activate python35
```
I then installed TPOT into this new environment:

```
(python35) H:>conda install tpot
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\anaconda3\envs\python35

  added / updated specs:
    - tpot


The following NEW packages will be INSTALLED:

  blas               pkgs/main/win-64::blas-1.0-mkl
  deap               conda-forge/win-64::deap-1.2.2-py35h830ac7b_0
  icc_rt             pkgs/main/win-64::icc_rt-2019.0.0-h0cc432a_1
  intel-openmp       conda-forge/win-64::intel-openmp-2021.2.0-h57928b3_616
  mkl                pkgs/main/win-64::mkl-2018.0.3-1
  numpy              pkgs/main/win-64::numpy-1.14.2-py35h5c71026_0
  pandas             conda-forge/win-64::pandas-0.23.4-py35h830ac7b_0
  pytz               conda-forge/noarch::pytz-2021.1-pyhd8ed1ab_0
  pywin32            conda-forge/win-64::pywin32-224-py35hfa6e2cd_1000
  requests           conda-forge/win-64::requests-2.13.0-py35_0
  scikit-learn       pkgs/main/win-64::scikit-learn-0.20.0-py35heebcf9a_1
  scipy              pkgs/main/win-64::scipy-1.1.0-py35hc28095f_0
  stopit             conda-forge/noarch::stopit-1.1.2-py_0
  tpot               conda-forge/win-64::tpot-0.9.5-py35_1
  tqdm               conda-forge/noarch::tqdm-4.60.0-pyhd8ed1ab_0
  update_checker     conda-forge/noarch::update_checker-0.18.0-pyh9f0ad1d_0


Proceed ([y]/n)? y
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(python35) H:>
```
When I try to import TPOT into this new environment I get:

```
(python35) H:>python
Python 3.5.5 | packaged by conda-forge | (default, Jul 24 2018, 01:52:17) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tpot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\anaconda3\envs\python35\lib\site-packages\tpot\__init__.py", line 27, in <module>
    from .tpot import TPOTClassifier, TPOTRegressor
  File "C:\anaconda3\envs\python35\lib\site-packages\tpot\tpot.py", line 26, in <module>
    from .base import TPOTBase
  File "C:\anaconda3\envs\python35\lib\site-packages\tpot\base.py", line 56, in <module>
    from update_checker import update_check
  File "C:\anaconda3\envs\python35\lib\site-packages\update_checker.py", line 74
    response = requests.get(f"https://pypi.org/pypi/{package}/json", timeout=1)
                                                                  ^
SyntaxError: invalid syntax
>>>
```

Any suggestions will be greatly appreciated,

Charles

**Comment by CBrauer** [comment]
Never mind.  I have given up on my project that requires Python 3,5.  To clean up my machine, I spend a day re-installing Anaconda Python.  I hate python. It's a miasma.
