### ISSUE TITLE
Traceback (most recent call last):   File "D:/program/PycharmProjects/泰坦尼克号/tpot.py", line 1, in <module>     from tpot import TPOTClassifier   File "D:\program\PycharmProjects\泰坦尼克号\tpot.py", line 1, in <module>     from tpot import TPOTClassifier ImportError: cannot import name 'TPOTClassifier' from 'tpot' (D:\program\PycharmProjects\泰坦尼克号\tpot.py)

### ISSUE THREAD

**Issue by breaker505** [EpistasisLab/tpot#1222]
[provide general introduction to the issue and why it is relevant to this repository]

## Context of the issue

[provide more detailed introduction to the issue itself and why it is relevant]

[the remaining entries are only necessary if you are reporting a bug]

## Process to reproduce the issue

[ordered list the process to finding and recreating the issue, example below]

1. User creates TPOT instance
2. User calls TPOT `fit()` function with training data
3. TPOT crashes with a `KeyError` after 5 generations

## Expected result

[describe what you would expect to have resulted from this process]

## Current result

[describe what you currently experience from this process, and thereby explain the bug]

## Possible fix

[not necessary, but suggest fixes or reasons for the bug]

## `name of issue` screenshot

[if relevant, include a screenshot]

**Comment by rachitk** [comment]
@breaker505 In the future, please follow the template provided - it makes it easier to debug and read your issue.

The problem described in the title of your issue is likely because you have named a file within your directory (or the script you are running itself) "tpot.py". Because of this, Python is attempting to import the relevant TPOT classes and functions from this file instead of from the installed TPOT package. Rename this file to something else (maybe "tpot_script.py" or something similar), and you should be able to import properly.
