### ISSUE TITLE
Fixed parameter

### ISSUE THREAD

**Issue by korcky** [EpistasisLab/tpot#620]
## Context of the issue

Sometimes I need to fixed some of model's parameters (without any changing in model's code) and when this parameter is value -- it's work fine (most of the time used non default value). Like this:

```python
config_dict = {
    'tpot_test.Test': {
        'a': np.arange(-1, 1, 0.1),
        'b': [1]
    }
}
```

But when this parameter should be method or class TPOT always used DEFAULT value

## Code example

```python
import numpy as np
from sklearn.base import RegressorMixin
from sklearn.metrics import r2_score
from tpot import TPOTRegressor


class Test(RegressorMixin):
    def __init__(self, a=None, b=None):
        print(a, b)
        self.a = a
        self.b = b

    def fit(self, X, y):
        return

    def predict(self, X):
        if self.b is r2_score:
            return self.a * X + 1
        else:
            return self.a * X

    def score(self, X, y, sample_weight=None):
        return r2_score(y_true=y, y_pred=self.predict(X))

    def get_params(self, deep=None):
        return {'a': self.a, 'b': self.b}


config_dict = {
    'tpot_test.Test': {
        'a': np.arange(-1, 1, 0.1),
        'b': [r2_score]
    }
}

tpot = TPOTRegressor(generations=5, population_size=5, cv=5, verbosity=1,
                     config_dict=config_dict)

tpot.fit(np.arange(0, 10, 1).reshape(-1, 1), (np.arange(0, 5, 0.5) + 1).reshape(-1, 1))
```

Result of `print(a, b)` always: `<value> None` (or sometimes `None None`)

**Comment by weixuanfu** [comment]
Is this the latest version of TPOT (v0.9)? I think I removed the DEFAULT in this [commit](https://github.com/rhiever/tpot/commit/5d6b73184c02600a85476856b9e58be6fd85d5de).

**Comment by korcky** [comment]
Oh, yeah, I forgot to update TPOT. It's fix problem with value parameter (now DEFAULT disappeared), but when using method or class exception appear:

## Code

```python
import numpy as np
from sklearn.base import RegressorMixin
from sklearn.metrics import r2_score
from tpot import TPOTRegressor


class Test(RegressorMixin):
    def __init__(self, a=None, b=None):
        print(a, b)
        self.a = a
        self.b = b

    def fit(self, X, y):
        return

    def predict(self, X):
        if self.b is r2_score:
            return self.a * X + 1
        else:
            return self.a * X

    def score(self, X, y, sample_weight=None):
        return r2_score(y_true=y, y_pred=self.predict(X))

    def get_params(self, deep=None):
        return {'a': self.a, 'b': self.b}


config_dict = {
    'tpot_test.Test': {
        'a': np.arange(-1, 1, 0.1),
        'b': [r2_score]
    }
}

tpot = TPOTRegressor(generations=5, population_size=5, cv=2, verbosity=1,
                     config_dict=config_dict)

tpot.fit(np.arange(0, 10, 1).reshape(-1, 1), (np.arange(0, 5, 0.5) + 1))
```

## Exception

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/tpot/base.py", line 586, in fit
    per_generation_function=self._check_periodic_pipeline
  File "/usr/local/lib/python3.5/site-packages/tpot/gp_deap.py", line 219, in eaMuPlusLambda
    per_generation_function()
  File "/usr/local/lib/python3.5/site-packages/tpot/base.py", line 848, in _check_periodic_pipeline
    self._update_top_pipeline()
  File "/usr/local/lib/python3.5/site-packages/tpot/base.py", line 632, in _update_top_pipeline
    raise RuntimeError('There was an error in the TPOT optimization '
RuntimeError: There was an error in the TPOT optimization process. This could be because the data
 was not formatted properly, or because data for a regression problem was provided to the TPOTClassifier object.
 Please make sure you passed the data to TPOT correctly.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tpot_test.py", line 37, in <module>
    config_dict=config_dict)
  File "/usr/local/lib/python3.5/site-packages/tpot/base.py", line 265, in __init__
    ArgBaseClass=ARGType
  File "/usr/local/lib/python3.5/site-packages/tpot/operator_utils.py", line 138, in TPOTOperatorClassFactory
    import_str, op_str, op_obj = source_decode(opsourse)
  File "/usr/local/lib/python3.5/site-packages/tpot/operator_utils.py", line 70, in source_decode
    exec('from {} import {}'.format(import_str, op_str))
  File "<string>", line 1, in <module>
  File "/Users/korcky/Documents/cindicator/cindicator-ai/tpot_test.py", line 39, in <module>
    tpot.fit(np.arange(0, 10, 1).reshape(-1, 1), (np.arange(0, 5, 0.5) + 1))
  File "/usr/local/lib/python3.5/site-packages/tpot/base.py", line 616, in fit
    raise e
  File "/usr/local/lib/python3.5/site-packages/tpot/base.py", line 609, in fit
    self._update_top_pipeline()
  File "/usr/local/lib/python3.5/site-packages/tpot/base.py", line 632, in _update_top_pipeline
    raise RuntimeError('There was an error in the TPOT optimization '
RuntimeError: There was an error in the TPOT optimization process. This could be because the data 
 was not formatted properly, or because data for a regression problem was provided to the TPOTClassifier object.
 Please make sure you passed the data to TPOT correctly.
```
But works fine if change `config_dict` to:
```
config_dict = {
    'tpot_test.Test': {
        'a': np.arange(-1, 1, 0.1),
        'b': [1]
    }
}
```

**Comment by weixuanfu** [comment]
How about using the `config_dict` as below?

**You need change `b` parameter to `score_func` though.**

```
config_dict = {
    'tpot_test.Test': {
        'a': np.arange(-1, 1, 0.1),
        'score_func': {
            'sklearn.metrics.r2_score': None
        }
    }
}

```

**Comment by korcky** [comment]
I guess this solution doesn't support custom parameters names (something besides `score_func`), because if not changing `b` parameter name to `score_func ` I will have same exception? But what if I will have more than one parameter that I want to fix? What if this parameters not a score function?

**Comment by rhiever** [comment]
I think the challenge here is that because the parameter you're fixing is a *function*, it requires this special setup in the config dictionary. It is easy enough to fix any numerical, string, etc. parameter as you did in your original comment.

**Comment by weixuanfu** [comment]
@korcky You are right. The demo is just a hacky way. I think a more general solution should be let TPOT to tell whether `'sklearn.metrics.r2_score'` is a callable function or sklearn's `BaseEsitmator` instead of checking the parameter name. @rhiever

**Comment by korcky** [comment]
That's will be great:
"more general solution should be let TPOT to tell whether `sklearn.metrics.r2_score` is a callable function or sklearn's `BaseEsitmator`"

**Comment by weixuanfu** [comment]
@korcky Hi, I just pushed #622 for this general solution. You may install that branch for testing with your customized model via the command below:

```
pip install --upgrade --no-deps --force-reinstall git+https://github.com/weixuanfu/tpot.git@refine_op_util
```

**Comment by korcky** [comment]
Thanks! It's work!

**Comment by weixuanfu** [comment]
I close this issue since the PR was merged to dev branch. Please feel free to re-open the issue (or comment further) if you have any more questions
