### ISSUE TITLE
Strange error when using a pre-trained model

### ISSUE THREAD

**Issue by CBrauer** [EpistasisLab/tpot#763]
Hey,

I have trained a model and saved it with joblib.dump.  The log of my training looks ok:
```
(base) H:\ML\BlogExperiments\Python\SKLearn\TPOT\40_50>python run.py
Operating system version.... Windows-10-10.0.17134-SP0
Python version is........... 3.6.5
pandas version is........... 0.23.0
numpy version is............ 1.14.3
tpot version is............. 0.9.5
Model dataset:
    BoxRatio  Thrust  Velocity  OnBalRun  vwapGain  Altitude
0     1.144   0.313     2.785     6.705     0.691         0
1     0.086  -0.447     0.399     0.832     0.416         0
2     0.539  -0.124     0.985     1.450     0.423         0
3     1.228   0.233     0.398     0.998     0.466         0
4     1.315   0.338     0.849     1.272     0.410         0
Size of resampled data:
 train shape...  (37647, 5) (37647,)
 test shape....  (16135, 5) (16135,)
Generation 1 - Current best internal CV score: 0.9180993425419419
Generation 2 - Current best internal CV score: 0.9180993425419419
Generation 3 - Current best internal CV score: 0.9180993425419419
Generation 4 - Current best internal CV score: 0.9180993425419419
Generation 5 - Current best internal CV score: 0.9180993425419419
...
Generation 35 - Current best internal CV score: 0.9198892481418662
Generation 36 - Current best internal CV score: 0.9198892481418662
Generation 37 - Current best internal CV score: 0.9198892481418662
Generation 38 - Current best internal CV score: 0.9198892481418662
Generation 39 - Current best internal CV score: 0.9198892481418662
Generation 40 - Current best internal CV score: 0.9199125746103063

Best pipeline: KNeighborsClassifier(CombineDFs(RandomForestClassifier(input_matrix, bootstrap=True, criterion=gini, max_features=0.3, min_samples_leaf=18, min_samples_split=4, n_estimators=100), SelectFromModel(GaussianNB(input_matrix), criterion=entropy, max_features=0.7500000000000001, n_estimators=100, threshold=0.05)), n_neighbors=1, p=2, weights=uniform)
Score on 0.9224358592773381 generations: 40 population: 50 scoring: f1 config: None

Total compute time was: 06:39:57
```

Here is a test program to load and test the trained model:

```
import platform
import sys
import numpy as np
import pandas as pd
import traceback
from sklearn.externals import joblib

def Main(predictors):
    print(' tpot predictors are: ', predictors)
    fields = predictors.strip().split(',')
    n_fields = len(fields)
    print('n_fields: ', n_fields)
    if n_fields == 5:
        try:
            clf = joblib.load('C:/sm/trained_models/tpot_model.pkl')
            row = np.array(predictors.split(',')).reshape(1,5)
            print('shape of row: ', row.shape)
            print(' row: ', row)
            predicted = clf.predict(row)[0]
            probabilities = clf.predict_proba(row)[0]
            probability = probabilities[predicted]
            print('predicted: ', predicted, ', probabilities: ', probabilities, ', probability: ', probability)
        except:
            print('Unexpected error in predictClassifyTpot: ')
            print(traceback.print_exc())

if __name__ == "__main__":
    print('Operating system version....', platform.platform())
    print("Python version is........... %s.%s.%s" % sys.version_info[:3])
    print('pandas version is...........', pd.__version__)
    print('numpy version is............', np.__version__)
    import tpot
    print('tpot version is.............', tpot.__version__)
    predictors = '0.215, -0.499, 1.654, 4.25, 1.559'
    Main(predictors)
```
When I run the test program I get the following error at the predict method:
```

Operating system version.... Windows-10-10.0.17134-SP0
Python version is........... 3.6.5
pandas version is........... 0.23.0
numpy version is............ 1.14.3
tpot version is............. 0.9.5
 tpot predictors are:  0.215, -0.499, 1.654, 4.25, 1.559
n_fields:  5
shape of row:  (1, 5)
 row:  [['0.215' ' -0.499' ' 1.654' ' 4.25' ' 1.559']]
Unexpected error in predictClassifyTpot:
Traceback (most recent call last):
  File "C:\sm\trained_models\Test\Test\Test.py", line 19, in Main
    predicted = clf.predict(row)[0]
  File "C:\Users\Charles\Anaconda3\lib\site-packages\sklearn\utils\metaestimators.py", line 115, in <lambda>
    out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)
  File "C:\Users\Charles\Anaconda3\lib\site-packages\sklearn\pipeline.py", line 306, in predict
    Xt = transform.transform(Xt)
  File "C:\Users\Charles\Anaconda3\lib\site-packages\sklearn\pipeline.py", line 768, in transform
    for name, trans, weight in self._iter())
  File "C:\Users\Charles\Anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py", line 779, in __call__
    while self.dispatch_one_batch(iterator):
  File "C:\Users\Charles\Anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py", line 625, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\Charles\Anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py", line 588, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "C:\Users\Charles\Anaconda3\lib\site-packages\sklearn\externals\joblib\_parallel_backends.py", line 111, in apply_async
    result = ImmediateResult(func)
  File "C:\Users\Charles\Anaconda3\lib\site-packages\sklearn\externals\joblib\_parallel_backends.py", line 332, in __init__
    self.results = batch()
  File "C:\Users\Charles\Anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "C:\Users\Charles\Anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py", line 131, in <listcomp>
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "C:\Users\Charles\Anaconda3\lib\site-packages\sklearn\pipeline.py", line 571, in _transform_one
    res = transformer.transform(X)
  File "C:\Users\Charles\Anaconda3\lib\site-packages\sklearn\pipeline.py", line 426, in _transform
    Xt = transform.transform(Xt)
  File "C:\Users\Charles\Anaconda3\lib\site-packages\tpot\builtins\stacking_estimator.py", line 87, in transform
    X_transformed = np.hstack((self.estimator.predict_proba(X), X))
  File "C:\Users\Charles\Anaconda3\lib\site-packages\sklearn\naive_bayes.py", line 104, in predict_proba
    return np.exp(self.predict_log_proba(X))
  File "C:\Users\Charles\Anaconda3\lib\site-packages\sklearn\naive_bayes.py", line 84, in predict_log_proba
    jll = self._joint_log_likelihood(X)
  File "C:\Users\Charles\Anaconda3\lib\site-packages\sklearn\naive_bayes.py", line 433, in _joint_log_likelihood
    n_ij -= 0.5 * np.sum(((X - self.theta_[i, :]) ** 2) /
TypeError: ufunc 'subtract' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')
None
Press any key to continue . . .
```
Any suggestions on how to fix this error would be greatly appreciated.
Charles
```

**Comment by weixuanfu** [comment]
Hmm, I am not sure what happened. Can the fitted pipeline that loaded from pickle file be used for the training data?

**Comment by CBrauer** [comment]
No, the error message aborts my test script.  I have tried other configurations that give an exported script that works o.k.  The pickle file aborts only with this file.

**Comment by CBrauer** [comment]
Hi Weixuan,
After installing updates to my operating system, and updates to Anaconda, I tried the test script again.  This time it worked.  All my other tpot scripts are also working fine.  Let's close this out because I cannot re-produce the problem. Must have been a gremlin.   Sorry for taking up you time.
Charles

**Comment by weixuanfu** [comment]
Ok, it is good to know that it works.
