### ISSUE TITLE
Invalid Pipeline generated by TPOT with test data

### ISSUE THREAD

**Issue by erico-souza** [EpistasisLab/tpot#852]
Found a pipeline with TPOT, but it does not execute the prediction, since it is generating features that do not match with the test data (Data used was attached in this message)

## Context of the issue

[provide more detailed introduction to the issue itself and why it is relevant]

[the remaining entries are only necessary if you are reporting a bug]

## Process to reproduce the issue

```python
import pandas as pd
from sklearn.pipeline import make_pipeline, make_union
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from tpot.builtins import StackingEstimator
train = pd.read_csv('../data/scene-train.csv')
test  = pd.read_csv('../data/scene-test.csv')
cols = list(train.columns)
Ys = ['Beach',
 'Sunset',
 'FallFoliage',
 'Field',
 'Mountain',
 'Urban']
features = [c for c in cols if c not in Ys]
print(features)
pipe_mountain =  make_pipeline(
    StackingEstimator(estimator=XGBClassifier(learning_rate=0.1, max_depth=7, min_child_weight=8, n_estimators=100, nthread=1, subsample=0.45)),
    RandomForestClassifier(bootstrap=False, criterion="gini", max_features=0.1, min_samples_leaf=10, min_samples_split=15, n_estimators=100)
)
pipe_mountain.fit(train[features], train['Mountain'])
results = pipe_mountain.predict(test[features])
```

## Expected result

I would expect the predictions for the specific label I requested.

## Current result

The error I am getting is related to features generated during the stacking phase that do not exist on the test data:

```python
Traceback (most recent call last):
  File "ml.py", line 76, in <module>
    pipes[cont].fit(train[features], train[y])
  File "/usr/local/lib/python3.5/dist-packages/sklearn/pipeline.py", line 265, in fit
    Xt, fit_params = self._fit(X, y, **fit_params)
  File "/usr/local/lib/python3.5/dist-packages/sklearn/pipeline.py", line 230, in _fit
    **fit_params_steps[name])
  File "/usr/local/lib/python3.5/dist-packages/sklearn/externals/joblib/memory.py", line 342, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/sklearn/pipeline.py", line 614, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
  File "/usr/local/lib/python3.5/dist-packages/sklearn/base.py", line 465, in fit_transform
    return self.fit(X, y, **fit_params).transform(X)
  File "/usr/local/lib/python3.5/dist-packages/tpot/builtins/stacking_estimator.py", line 87, in transform
    X_transformed = np.hstack((self.estimator.predict_proba(X), X))
  File "/usr/local/lib/python3.5/dist-packages/xgboost/sklearn.py", line 802, in predict_proba
    validate_features=validate_features)
  File "/usr/local/lib/python3.5/dist-packages/xgboost/core.py", line 1218, in predict
    self._validate_features(data)
  File "/usr/local/lib/python3.5/dist-packages/xgboost/core.py", line 1541, in _validate_features
    data.feature_names))
ValueError: feature_names mismatch: ['Att1', 'Att2', 'Att3', 'Att4', 'Att5', 'Att6', 'Att7', 'Att8', 'Att9', 'Att10', 'Att11', 'Att12', 'Att13', 'Att14', 'Att15', 'Att16', 'Att17', 'Att18', 'Att19', 'Att20', 'Att21', 'Att22', 'Att23', 'Att24', 'Att25', 'Att26', 'Att27', 'Att28', 'Att29', 'Att30', 'Att31', 'Att32', 'Att33', 'Att34', 'Att35', 'Att36', 'Att37', 'Att38', 'Att39', 'Att40', 'Att41', 'Att42', 'Att43', 'Att44', 'Att45', 'Att46', 'Att47', 'Att48', 'Att49', 'Att50', 'Att51', 'Att52', 'Att53', 'Att54', 'Att55', 'Att56', 'Att57', 'Att58', 'Att59', 'Att60', 'Att61', 'Att62', 'Att63', 'Att64', 'Att65', 'Att66', 'Att67', 'Att68', 'Att69', 'Att70', 'Att71', 'Att72', 'Att73', 'Att74', 'Att75', 'Att76', 'Att77', 'Att78', 'Att79', 'Att80', 'Att81', 'Att82', 'Att83', 'Att84', 'Att85', 'Att86', 'Att87', 'Att88', 'Att89', 'Att90', 'Att91', 'Att92', 'Att93', 'Att94', 'Att95', 'Att96', 'Att97', 'Att98', 'Att99', 'Att100', 'Att101', 'Att102', 'Att103', 'Att104', 'Att105', 'Att106', 'Att107', 'Att108', 'Att109', 'Att110', 'Att111', 'Att112', 'Att113', 'Att114', 'Att115', 'Att116', 'Att117', 'Att118', 'Att119', 'Att120', 'Att121', 'Att122', 'Att123', 'Att124', 'Att125', 'Att126', 'Att127', 'Att128', 'Att129', 'Att130', 'Att131', 'Att132', 'Att133', 'Att134', 'Att135', 'Att136', 'Att137', 'Att138', 'Att139', 'Att140', 'Att141', 'Att142', 'Att143', 'Att144', 'Att145', 'Att146', 'Att147', 'Att148', 'Att149', 'Att150', 'Att151', 'Att152', 'Att153', 'Att154', 'Att155', 'Att156', 'Att157', 'Att158', 'Att159', 'Att160', 'Att161', 'Att162', 'Att163', 'Att164', 'Att165', 'Att166', 'Att167', 'Att168', 'Att169', 'Att170', 'Att171', 'Att172', 'Att173', 'Att174', 'Att175', 'Att176', 'Att177', 'Att178', 'Att179', 'Att180', 'Att181', 'Att182', 'Att183', 'Att184', 'Att185', 'Att186', 'Att187', 'Att188', 'Att189', 'Att190', 'Att191', 'Att192', 'Att193', 'Att194', 'Att195', 'Att196', 'Att197', 'Att198', 'Att199', 'Att200', 'Att201', 'Att202', 'Att203', 'Att204', 'Att205', 'Att206', 'Att207', 'Att208', 'Att209', 'Att210', 'Att211', 'Att212', 'Att213', 'Att214', 'Att215', 'Att216', 'Att217', 'Att218', 'Att219', 'Att220', 'Att221', 'Att222', 'Att223', 'Att224', 'Att225', 'Att226', 'Att227', 'Att228', 'Att229', 'Att230', 'Att231', 'Att232', 'Att233', 'Att234', 'Att235', 'Att236', 'Att237', 'Att238', 'Att239', 'Att240', 'Att241', 'Att242', 'Att243', 'Att244', 'Att245', 'Att246', 'Att247', 'Att248', 'Att249', 'Att250', 'Att251', 'Att252', 'Att253', 'Att254', 'Att255', 'Att256', 'Att257', 'Att258', 'Att259', 'Att260', 'Att261', 'Att262', 'Att263', 'Att264', 'Att265', 'Att266', 'Att267', 'Att268', 'Att269', 'Att270', 'Att271', 'Att272', 'Att273', 'Att274', 'Att275', 'Att276', 'Att277', 'Att278', 'Att279', 'Att280', 'Att281', 'Att282', 'Att283', 'Att284', 'Att285', 'Att286', 'Att287', 'Att288', 'Att289', 'Att290', 'Att291', 'Att292', 'Att293', 'Att294'] ['f0', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'f10', 'f11', 'f12', 'f13', 'f14', 'f15', 'f16', 'f17', 'f18', 'f19', 'f20', 'f21', 'f22', 'f23', 'f24', 'f25', 'f26', 'f27', 'f28', 'f29', 'f30', 'f31', 'f32', 'f33', 'f34', 'f35', 'f36', 'f37', 'f38', 'f39', 'f40', 'f41', 'f42', 'f43', 'f44', 'f45', 'f46', 'f47', 'f48', 'f49', 'f50', 'f51', 'f52', 'f53', 'f54', 'f55', 'f56', 'f57', 'f58', 'f59', 'f60', 'f61', 'f62', 'f63', 'f64', 'f65', 'f66', 'f67', 'f68', 'f69', 'f70', 'f71', 'f72', 'f73', 'f74', 'f75', 'f76', 'f77', 'f78', 'f79', 'f80', 'f81', 'f82', 'f83', 'f84', 'f85', 'f86', 'f87', 'f88', 'f89', 'f90', 'f91', 'f92', 'f93', 'f94', 'f95', 'f96', 'f97', 'f98', 'f99', 'f100', 'f101', 'f102', 'f103', 'f104', 'f105', 'f106', 'f107', 'f108', 'f109', 'f110', 'f111', 'f112', 'f113', 'f114', 'f115', 'f116', 'f117', 'f118', 'f119', 'f120', 'f121', 'f122', 'f123', 'f124', 'f125', 'f126', 'f127', 'f128', 'f129', 'f130', 'f131', 'f132', 'f133', 'f134', 'f135', 'f136', 'f137', 'f138', 'f139', 'f140', 'f141', 'f142', 'f143', 'f144', 'f145', 'f146', 'f147', 'f148', 'f149', 'f150', 'f151', 'f152', 'f153', 'f154', 'f155', 'f156', 'f157', 'f158', 'f159', 'f160', 'f161', 'f162', 'f163', 'f164', 'f165', 'f166', 'f167', 'f168', 'f169', 'f170', 'f171', 'f172', 'f173', 'f174', 'f175', 'f176', 'f177', 'f178', 'f179', 'f180', 'f181', 'f182', 'f183', 'f184', 'f185', 'f186', 'f187', 'f188', 'f189', 'f190', 'f191', 'f192', 'f193', 'f194', 'f195', 'f196', 'f197', 'f198', 'f199', 'f200', 'f201', 'f202', 'f203', 'f204', 'f205', 'f206', 'f207', 'f208', 'f209', 'f210', 'f211', 'f212', 'f213', 'f214', 'f215', 'f216', 'f217', 'f218', 'f219', 'f220', 'f221', 'f222', 'f223', 'f224', 'f225', 'f226', 'f227', 'f228', 'f229', 'f230', 'f231', 'f232', 'f233', 'f234', 'f235', 'f236', 'f237', 'f238', 'f239', 'f240', 'f241', 'f242', 'f243', 'f244', 'f245', 'f246', 'f247', 'f248', 'f249', 'f250', 'f251', 'f252', 'f253', 'f254', 'f255', 'f256', 'f257', 'f258', 'f259', 'f260', 'f261', 'f262', 'f263', 'f264', 'f265', 'f266', 'f267', 'f268', 'f269', 'f270', 'f271', 'f272', 'f273', 'f274', 'f275', 'f276', 'f277', 'f278', 'f279', 'f280', 'f281', 'f282', 'f283', 'f284', 'f285', 'f286', 'f287', 'f288', 'f289', 'f290', 'f291', 'f292', 'f293']
expected Att158, Att70, Att34, Att205, Att187, Att176, Att14, Att119, Att231, Att72, Att265, Att4, Att242, Att270, Att262, Att12, Att203, Att18, Att216, Att105, Att157, Att136, Att269, Att108, Att61, Att90, Att102, Att83, Att259, Att264, Att87, Att17, Att282, Att47, Att20, Att190, Att38, Att267, Att139, Att271, Att193, Att48, Att75, Att197, Att30, Att62, Att69, Att208, Att182, Att2, Att253, Att112, Att33, Att134, Att129, Att226, Att292, Att183, Att21, Att173, Att235, Att67, Att131, Att239, Att166, Att142, Att164, Att113, Att45, Att41, Att147, Att92, Att200, Att31, Att116, Att195, Att274, Att243, Att293, Att154, Att54, Att241, Att81, Att64, Att171, Att277, Att85, Att76, Att152, Att256, Att151, Att137, Att170, Att91, Att104, Att66, Att207, Att140, Att227, Att181, Att289, Att223, Att53, Att74, Att16, Att155, Att219, Att233, Att13, Att168, Att82, Att111, Att117, Att261, Att204, Att44, Att71, Att22, Att135, Att63, Att3, Att184, Att124, Att179, Att217, Att93, Att287, Att156, Att230, Att28, Att240, Att288, Att201, Att210, Att130, Att56, Att107, Att285, Att258, Att65, Att127, Att133, Att175, Att255, Att278, Att160, Att60, Att238, Att180, Att222, Att248, Att209, Att46, Att249, Att206, Att132, Att281, Att284, Att35, Att202, Att263, Att23, Att128, Att236, Att100, Att213, Att10, Att191, Att199, Att185, Att247, Att153, Att8, Att163, Att283, Att225, Att146, Att58, Att29, Att224, Att49, Att159, Att189, Att5, Att6, Att110, Att86, Att167, Att244, Att237, Att68, Att246, Att161, Att294, Att97, Att26, Att150, Att272, Att78, Att252, Att51, Att106, Att118, Att232, Att148, Att7, Att250, Att122, Att162, Att94, Att9, Att145, Att276, Att138, Att24, Att79, Att89, Att114, Att42, Att286, Att55, Att52, Att141, Att88, Att144, Att11, Att98, Att37, Att165, Att280, Att192, Att194, Att84, Att254, Att228, Att211, Att126, Att169, Att290, Att73, Att257, Att260, Att279, Att172, Att266, Att32, Att123, Att109, Att174, Att198, Att221, Att275, Att99, Att229, Att25, Att115, Att57, Att186, Att215, Att273, Att188, Att149, Att59, Att177, Att291, Att214, Att36, Att220, Att96, Att50, Att40, Att15, Att218, Att196, Att268, Att121, Att103, Att77, Att80, Att178, Att101, Att212, Att234, Att245, Att27, Att43, Att125, Att1, Att95, Att120, Att251, Att19, Att39, Att143 in input data
training data did not have the following fields: f16, f32, f66, f161, f191, f272, f141, f180, f229, f64, f126, f59, f288, f106, f93, f182, f128, f241, f111, f120, f254, f190, f60, f82, f189, f77, f208, f7, f21, f23, f108, f253, f198, f48, f266, f27, f110, f36, f38, f46, f89, f86, f174, f228, f252, f209, f186, f99, f10, f92, f100, f94, f103, f118, f162, f258, f4, f54, f1, f267, f281, f45, f79, f51, f149, f147, f134, f157, f206, f178, f81, f290, f164, f213, f175, f169, f50, f139, f30, f220, f262, f278, f33, f34, f24, f270, f218, f203, f40, f176, f225, f179, f275, f244, f137, f234, f87, f168, f69, f273, f183, f84, f28, f20, f31, f231, f204, f163, f140, f256, f133, f199, f289, f170, f0, f56, f113, f217, f263, f292, f55, f2, f274, f97, f15, f52, f201, f242, f130, f29, f148, f207, f116, f42, f233, f104, f83, f172, f240, f61, f112, f121, f181, f239, f6, f25, f222, f226, f261, f269, f49, f132, f248, f284, f14, f119, f80, f166, f78, f152, f44, f216, f72, f154, f102, f117, f91, f145, f142, f122, f75, f235, f39, f114, f95, f68, f167, f11, f71, f155, f200, f237, f194, f280, f57, f58, f214, f236, f276, f165, f96, f265, f5, f127, f131, f260, f17, f47, f279, f90, f188, f74, f88, f243, f41, f185, f251, f101, f257, f259, f135, f65, f158, f291, f286, f159, f9, f62, f26, f146, f115, f153, f177, f285, f197, f277, f8, f13, f125, f35, f282, f150, f67, f245, f129, f268, f255, f160, f22, f202, f227, f230, f76, f173, f247, f136, f18, f12, f151, f193, f249, f156, f271, f195, f264, f223, f250, f283, f293, f105, f19, f205, f211, f224, f73, f196, f246, f109, f123, f143, f124, f63, f144, f37, f210, f187, f219, f215, f192, f184, f171, f232, f212, f221, f98, f238, f43, f53, f138, f287, f70, f85, f3, f107
```

## Possible fix

[not necessary, but suggest fixes or reasons for the bug]

## `name of issue` screenshot

TPOT version (using on python 3.5):
```python
---
Metadata-Version: 2.0
Name: TPOT
Version: 0.9.5
Summary: Tree-based Pipeline Optimization Tool
Home-page: https://github.com/EpistasisLab/tpot
Author: Randal S. Olson
Author-email: rso@randalolson.com
Installer: pip
License: GNU/LGPLv3
Location: /usr/local/lib/python3.5/dist-packages
Requires: scikit-learn, tqdm, pandas, numpy, stopit, update-checker, deap, scipy
Classifiers:
  Intended Audience :: Science/Research
  License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.4
  Programming Language :: Python :: 3.5
  Programming Language :: Python :: 3.6
  Topic :: Scientific/Engineering :: Artificial Intelligence
Entry-points:
  [console_scripts]
  tpot = tpot:main
```

**Comment by weixuanfu** [comment]
You may try to convert `train[features]` to `np.ndarray` for avoiding this feature name checking in xgboost, like `pipe_mountain.fit(train[features].values, train['Mountain'].values)`

**Comment by erico-souza** [comment]
Thanks for the help. It works! It would be nice if XGBoost worked in the same way as normal sklearn algorithnts

Erico
