### ISSUE TITLE
issue with TPOT fit

### ISSUE THREAD

**Issue by rthapa26** [EpistasisLab/tpot#957]
Hi, I am getting the following error. Could you provide any suggestion what I am doing wrong? Thanks

>>> pipeline_optimizer.fit(X_train, y_train)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tpot/base.py", line 630, in fit
    features, target = self._check_dataset(features, target, sample_weight)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tpot/base.py", line 1153, in _check_dataset
    if np.any(np.isnan(features)):
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

**Comment by weixuanfu** [comment]
Could you please provide more details about this issue, like versions of TPOT and its dependencies? Also could you please provide codes for reproducing this issue?
