### ISSUE TITLE
error with input data format

### ISSUE THREAD

**Issue by rthapa26** [EpistasisLab/tpot#958]
Hi, 

I am getting an error with input data format. I am wondering how that input format of features and label should be. Thanks

>>> pipeline_optimizer.fit(X_train, y_train)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tpot/base.py", line 1164, in _check_dataset
    X, y = check_X_y(features, target, accept_sparse=True, dtype=None)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/utils/validation.py", line 724, in check_X_y
    y = column_or_1d(y, warn=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/utils/validation.py", line 760, in column_or_1d
    raise ValueError("bad input shape {0}".format(shape))
ValueError: bad input shape (36, 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tpot/base.py", line 630, in fit
    features, target = self._check_dataset(features, target, sample_weight)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tpot/base.py", line 1177, in _check_dataset
    'Error: Input data is not in a valid format. Please confirm '
ValueError: Error: Input data is not in a valid format. Please confirm that the input data is scikit-learn compatible. For example, the features must be a 2-D array and target labels must be a 1-D array.

**Comment by weixuanfu** [comment]
Could you please provide more details about this issue, like versions of TPOT and its dependencies? Also could you please provide codes for reproducing this issue?

Based on the error message, the reason maybe that the input X is not a 2-D array or y is not a 1-D array. Please reshape them based on the error message.
